### PR TITLE
Fifth part

### PR DESCRIPTION
**Pull request by serejkaaa512**
[Review on Reviewable](https://reviewable.io/reviews/rurust/rustonomicon/5)

### CODE REVIEW

**Comment by mkpankov** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/checked-uninit.md, line 3 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjaXfKBLKCGUooDQjc:-KCjaXfKBLKCGUooDQjd:-1584025056) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/checked-uninit.md#L3)):*
Как и в Си, в Rust все переменные ...

Си - здесь и далее

---

*[src/checked-uninit.md, line 71 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjawRH2OrwexdkR4Zc:-KCjawRITV_g_ZivZrpy:938363854) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/checked-uninit.md#L71)):*
Конечно, несмотря на то, что в анализе не участвуют настоящие значения, компилятор довольно хорошо понимает зависимостей и потока выполнения.

---

*[src/drop-flags.md, line 11 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjbZ8AZg4ws4cqNUC6:-KCjbZ8AZg4ws4cqNUC7:851428271) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L11)):*
присваивания

Здесь и далее

---

*[src/drop-flags.md, line 13 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjbfMj10foW4UBL9dZ:-KCjbfMj10foW4UBL9d_:1332992324) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L13)):*
безусловно не выполняет его:

---

*[src/drop-flags.md, line 26 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjbwk15_uyEEVSFvV9:-KCjbwk2V4uG3HrRFQL2:-935447867) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L26)):*
неинициализированной, *флаг удаления* для неё переключается.

---

*[src/drop-flags.md, line 43 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjcB3Uj5QV0MlM7gCX:-KCjcB3Uj5QV0MlM7gCY:702296266) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L43)):*
ветвлением, где внутри веток наблюдается похожее поведение в отношении инициализации, ...

---

*[src/drop-flags.md, line 73 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjcZupF0hxc5a8vdHn:-KCjcZupF0hxc5a8vdHo:1105869646) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L73)):*
Конечно, в данном случае ...

---

*[src/drop-flags.md, line 89 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjciAZmOtoZ9YxrOJq:-KCjciAZmOtoZ9YxrOJr:1813892667) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L89)):*
в кадр стека, которому они по-настоящему и принадлежат.

---

*[src/drop-flags.md, line 95 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjcwOVMVNYctmXEqOt:-KCjcwOVMVNYctmXEqOu:-1308854631) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L95)):*
..., Rust позволяет легко контролировать её.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Comment by serejkaaa512** [comment]
Review status: 1 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/checked-uninit.md, line 3 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjaXfKBLKCGUooDQjc:-KCkY5CJtFtTEvVZ5Bu2:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/checked-uninit.md#L3)):*
Done.

---

*[src/checked-uninit.md, line 71 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjawRH2OrwexdkR4Zc:-KCkY5qo-eLjOEf3UPiP:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/checked-uninit.md#L71)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Comment by serejkaaa512** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/drop-flags.md, line 11 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjbZ8AZg4ws4cqNUC6:-KCkZSkeJJuRa18iyrYI:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L11)):*
Done.

---

*[src/drop-flags.md, line 13 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjbfMj10foW4UBL9dZ:-KCkZTrsnny_5v0NTAez:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L13)):*
Done.

---

*[src/drop-flags.md, line 26 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjbwk15_uyEEVSFvV9:-KCkZUTF9ZIZGODX0Oj1:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L26)):*
Done.

---

*[src/drop-flags.md, line 43 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjcB3Uj5QV0MlM7gCX:-KCkZUxaEXfn7X0k8i_7:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L43)):*
Done.

---

*[src/drop-flags.md, line 73 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjcZupF0hxc5a8vdHn:-KCkZVTkEwtTGkMavP5T:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L73)):*
Done.

---

*[src/drop-flags.md, line 89 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjciAZmOtoZ9YxrOJq:-KCkZW4ArXyhDJpfBpQO:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L89)):*
Done.

---

*[src/drop-flags.md, line 95 \[r1\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCjcwOVMVNYctmXEqOt:-KCkZXTOpjjIkPDCx-FQ:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/81158605ab8b8a133104130c5bf16729ce518969/src/drop-flags.md#L95)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Comment by mkpankov** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/unchecked-uninit.md, line 16 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCkYYSLYetgpb82-bhO:-KCkYYSLYetgpb82-bhP:900839220) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L16)):*
К сожалению, это может привести к возникновению кучи проблем. Присваивание ...

Присваивание - здесь и далее

---

*[src/unchecked-uninit.md, line 24 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCkYpNtnuK6UkpBbOyx:-KCkYpNuPG9WZGBfjM2T:523662030) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L24)):*
с системным распределителем памяти, который возвращает сырой указатель на неинициализированную память.

---

*[src/unchecked-uninit.md, line 33 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCkZ78kXRwL7l3o7Uuu:-KCkZ78lbaPVRjcjsEhm:1452365397) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L33)):*
копирует из src в dest столько памяти, сколько занимают `count` экземпляров типа T.

---

*[src/unchecked-uninit.md, line 73 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_3e7uHhFrgAVW3fM:-KCk_3e7uHhFrgAVW3fN:511915288) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L73)):*
которые не реализуют `Drop` сами и не содержат типы, реализующие его, потому что ...

---

*[src/unchecked-uninit.md, line 80 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_GhKetDoVoHjDcnP:-KCk_GhKetDoVoHjDcnQ:756310098) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L80)):*
Каждый путь выполнения

---

*[src/unchecked-uninit.md, line 82 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_MnfV5ILZ5EWKiV1:-KCk_MngNgxkiYCyptGy:-336037985) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L82)):*
Это включает в себя поведение кода в случае паники.

---

*[src/uninitialized.md, line 4 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_f8sHyc4H_aYT7Ic:-KCk_f8sHyc4H_aYT7Id:-940224718) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/uninitialized.md#L4)):*
В таком состоянии значения в памяти представляют собой кучку неопределённых бит, о которых даже неизвестно, смогут ли они правильно представить состояние значения того типа, который разместится в этой памяти.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Comment by serejkaaa512** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/unchecked-uninit.md, line 16 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCkYYSLYetgpb82-bhO:-KCkf6ligo6KIvTXQlJc:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L16)):*
Done.

---

*[src/unchecked-uninit.md, line 24 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCkYpNtnuK6UkpBbOyx:-KCkf7LhK-XM18nswBLg:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L24)):*
Done.

---

*[src/unchecked-uninit.md, line 33 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCkZ78kXRwL7l3o7Uuu:-KCkf7zDv1Y9Y7CxaiTj:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L33)):*
Done.

---

*[src/unchecked-uninit.md, line 73 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_3e7uHhFrgAVW3fM:-KCkf8fv6dJPxks-JQX3:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L73)):*
Done.

---

*[src/unchecked-uninit.md, line 80 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_GhKetDoVoHjDcnP:-KCkf98wQI3_7c31QPmL:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L80)):*
Done.

---

*[src/unchecked-uninit.md, line 82 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_MnfV5ILZ5EWKiV1:-KCkf9ZWmxoKlbFn-H1O:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/unchecked-uninit.md#L82)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Comment by serejkaaa512** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/uninitialized.md, line 4 \[r2\]](https://reviewable.io:443/reviews/rurust/rustonomicon/5#-KCk_f8sHyc4H_aYT7Ic:-KCkfSGnyIXnkmP3JzO0:-499146009) ([raw file](https://github.com/rurust/rustonomicon/blob/2a7c417625dc7c465751964dbce4af80ac7edefc/src/uninitialized.md#L4)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Comment by mkpankov** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustonomicon/5)*

**Pull request merged**
